import a11y from './a11y';
import biddingInit from './bidding';
import headRandomize from './layout/header-randomize';
import modalInit from './modal';
import recordAudio from './searchForm/recordAudio';
import searchFormReset from './searchForm/reset';
import searchFormSelect from './searchForm/select';
import searchResults from './searchResults';
import selectNavigation from './selectNavigation';
import sliderInit from './slider';

a11y();
biddingInit();
headRandomize();
modalInit();
recordAudio();
searchResults();
searchFormReset();
searchFormSelect();
selectNavigation();
sliderInit();
