import a11y from './a11y';
import ariaMenusInit from './ariaMenus';
import biddingInit from './bidding';
import flagFirstAccess from './flag-first-access';
import headerRandomize from './layout/header-randomize';
import likeDetailsInit from './like-a-details';
import menuResetter from './menuResetter';
import modalInit from './modal';
import recordAudio from './searchForm/recordAudio';
import searchFormReset from './searchForm/reset';
import searchFormSelect from './searchForm/select';
import searchResults from './searchResults';
import selectNavigation from './selectNavigation';
import setFromQueryStrings from './setFromQueryString';
import sliderInit from './slider';
import videoGalleryInit from './videoGallery';

a11y();
ariaMenusInit();
biddingInit();
flagFirstAccess();
headerRandomize();
likeDetailsInit();
menuResetter();
modalInit();
recordAudio();
searchFormReset();
searchFormSelect();
searchResults();
selectNavigation();
setFromQueryStrings();
sliderInit();
videoGalleryInit();
