version: "3.5"
services:
    api:
        build:
          context: .
          args:
            - AUTH_FOLDER_INSIDE_CONTAINER=${AUTH_FOLDER_INSIDE_CONTAINER}
            - JSON_KEY_FILENAME=${JSON_KEY_FILENAME}
            - GOOGLE_CLOUD_PROJECT_NAME=${GOOGLE_CLOUD_PROJECT_NAME}
        container_name: dialogflow_proxy_api
        restart: unless-stopped
        environment:
            PORT: 8080
            GOOGLE_APPLICATION_CREDENTIALS: ${AUTH_FOLDER_INSIDE_CONTAINER}${JSON_KEY_FILENAME}
            GOOGLE_CLOUD_PROJECT_NAME: ${GOOGLE_CLOUD_PROJECT_NAME}
        ports:
            - ${BIND_INTERFACE}:${BIND_INTERFACE_PORT}:8080
        networks:
            - external
        logging:
          driver: "json-file"
          options:
            max-file: '100'
            max-size: 1m
networks:
    external:
